// AUTO-GENERATED by scripts/roadmap-to-ts.ts from docs/UNIT_ROADMAP.md. Do not edit by hand.
// The V2 spine: every unit in factory order with the standards it teaches.
// A unit's lessons are resolved from the lesson manifest at runtime
// (lib/journey-v2/catalog.ts), so this file never claims a lesson exists.

export type Band = 0 | 1 | 2 | 3 | 4;

export interface RoadmapUnit {
  /** "k-u1", "g2-u3" */
  id: string;
  /** Catalog grade string, matches LessonDef.grade: "Kindergarten", "2nd Grade" */
  grade: string;
  band: Band;
  unitNo: number;
  /** Roadmap name when the roadmap has one, else "Unit N" */
  name: string;
  /** CCSS ids in roadmap order */
  standards: string[];
  /** QuizDef id of the unit exam (may not exist in the manifest yet) */
  examId: string;
}

export const ROADMAP_UNITS: RoadmapUnit[] = [
  {
    "id": "k-u1",
    "grade": "Kindergarten",
    "band": 0,
    "unitNo": 1,
    "name": "Reading Foundations",
    "standards": [
      "RF.K.1a",
      "RF.K.1b",
      "RF.K.1c",
      "RF.K.1d",
      "RF.K.2a",
      "RF.K.2b",
      "RF.K.3b",
      "RL.K.1",
      "RL.K.3",
      "RL.K.5",
      "RL.K.6",
      "K.L.6"
    ],
    "examId": "unit-1-exam"
  },
  {
    "id": "k-u2",
    "grade": "Kindergarten",
    "band": 0,
    "unitNo": 2,
    "name": "Sound & Letter Lab",
    "standards": [
      "RF.K.2c",
      "RF.K.2d",
      "RF.K.2e",
      "RF.K.3a",
      "RF.K.3c",
      "RL.K.2",
      "RL.K.4",
      "K.L.1"
    ],
    "examId": "unit-2-exam"
  },
  {
    "id": "k-u3",
    "grade": "Kindergarten",
    "band": 0,
    "unitNo": 3,
    "name": "Super Readers",
    "standards": [
      "RF.K.3d",
      "RF.K.4",
      "RL.K.7",
      "RL.K.9",
      "RL.K.10",
      "K.L.4",
      "K.L.5",
      "K.L.2"
    ],
    "examId": "unit-3-exam"
  },
  {
    "id": "k-u4",
    "grade": "Kindergarten",
    "band": 0,
    "unitNo": 4,
    "name": "Fact Finders (informational text)",
    "standards": [
      "RI.K.1",
      "RI.K.2",
      "RI.K.3",
      "RI.K.4",
      "RI.K.5",
      "RI.K.6",
      "RI.K.7",
      "RI.K.8",
      "RI.K.9",
      "RI.K.10"
    ],
    "examId": "unit-4-exam"
  },
  {
    "id": "g1-u1",
    "grade": "1st Grade",
    "band": 1,
    "unitNo": 1,
    "name": "Unit 1",
    "standards": [
      "RF.1.1a",
      "RF.1.2b",
      "RF.1.2c",
      "RL.1.1",
      "RL.1.2",
      "RI.1.1",
      "RI.1.2",
      "L.1.4",
      "L.1.4a",
      "L.1.4b"
    ],
    "examId": "g1-unit-1-exam"
  },
  {
    "id": "g1-u2",
    "grade": "1st Grade",
    "band": 1,
    "unitNo": 2,
    "name": "Unit 2",
    "standards": [
      "RF.1.2d",
      "RF.1.4b",
      "RF.1.4c",
      "RL.1.3",
      "RL.1.4",
      "RI.1.3",
      "RI.1.4",
      "L.1.4c",
      "L.1.5",
      "L.1.5a"
    ],
    "examId": "g1-unit-2-exam"
  },
  {
    "id": "g1-u3",
    "grade": "1st Grade",
    "band": 1,
    "unitNo": 3,
    "name": "Unit 3",
    "standards": [
      "RF.1.3a",
      "RF.1.3b",
      "RF.1.3c",
      "RL.1.5",
      "RL.1.6",
      "RI.1.5",
      "RI.1.6",
      "L.1.5b",
      "L.1.5c",
      "L.1.5d"
    ],
    "examId": "g1-unit-3-exam"
  },
  {
    "id": "g1-u4",
    "grade": "1st Grade",
    "band": 1,
    "unitNo": 4,
    "name": "Unit 4",
    "standards": [
      "RF.1.3d",
      "RF.1.3e",
      "RF.1.3f",
      "RL.1.7",
      "RL.1.9",
      "RI.1.7",
      "RI.1.8",
      "L.1.6",
      "L.1.1",
      "L.1.2"
    ],
    "examId": "g1-unit-4-exam"
  },
  {
    "id": "g1-u5",
    "grade": "1st Grade",
    "band": 1,
    "unitNo": 5,
    "name": "Unit 5",
    "standards": [
      "RF.1.3g",
      "RF.1.4a",
      "RL.1.10",
      "RI.1.9",
      "RI.1.10"
    ],
    "examId": "g1-unit-5-exam"
  },
  {
    "id": "g2-u1",
    "grade": "2nd Grade",
    "band": 2,
    "unitNo": 1,
    "name": "Unit 1",
    "standards": [
      "RF.2.3",
      "RF.2.3a",
      "RF.2.3b",
      "RL.2.1",
      "RL.2.2",
      "RL.2.3",
      "RI.2.1",
      "RI.2.2",
      "RI.2.3",
      "L.2.4",
      "L.2.4a",
      "L.2.4b",
      "L.2.4c"
    ],
    "examId": "g2-unit-1-exam"
  },
  {
    "id": "g2-u2",
    "grade": "2nd Grade",
    "band": 2,
    "unitNo": 2,
    "name": "Unit 2",
    "standards": [
      "RF.2.3c",
      "RF.2.3d",
      "RF.2.3e",
      "RL.2.4",
      "RL.2.5",
      "RL.2.6",
      "RI.2.4",
      "RI.2.5",
      "RI.2.6",
      "L.2.4d",
      "L.2.4e",
      "L.2.5",
      "L.2.5a"
    ],
    "examId": "g2-unit-2-exam"
  },
  {
    "id": "g2-u3",
    "grade": "2nd Grade",
    "band": 2,
    "unitNo": 3,
    "name": "Unit 3",
    "standards": [
      "RF.2.3f",
      "RF.2.4",
      "RF.2.4a",
      "RL.2.7",
      "RL.2.9",
      "RL.2.10",
      "RI.2.7",
      "RI.2.8",
      "RI.2.9",
      "L.2.5b",
      "L.2.6",
      "L.2.1",
      "L.2.2"
    ],
    "examId": "g2-unit-3-exam"
  },
  {
    "id": "g2-u4",
    "grade": "2nd Grade",
    "band": 2,
    "unitNo": 4,
    "name": "Unit 4",
    "standards": [
      "RF.2.4b",
      "RF.2.4c",
      "RI.2.10",
      "L.2.3"
    ],
    "examId": "g2-unit-4-exam"
  },
  {
    "id": "g3-u1",
    "grade": "3rd Grade",
    "band": 3,
    "unitNo": 1,
    "name": "Unit 1",
    "standards": [
      "RF.3.3",
      "RF.3.3a",
      "RF.3.3b",
      "RL.3.1",
      "RL.3.2",
      "RL.3.3",
      "RI.3.1",
      "RI.3.2",
      "RI.3.3",
      "L.3.4",
      "L.3.4a",
      "L.3.4b",
      "L.3.4c"
    ],
    "examId": "g3-unit-1-exam"
  },
  {
    "id": "g3-u2",
    "grade": "3rd Grade",
    "band": 3,
    "unitNo": 2,
    "name": "Unit 2",
    "standards": [
      "RF.3.3c",
      "RF.3.3d",
      "RF.3.4",
      "RL.3.4",
      "RL.3.5",
      "RL.3.6",
      "RI.3.4",
      "RI.3.5",
      "RI.3.6",
      "L.3.4d",
      "L.3.5",
      "L.3.5a",
      "L.3.5b"
    ],
    "examId": "g3-unit-2-exam"
  },
  {
    "id": "g3-u3",
    "grade": "3rd Grade",
    "band": 3,
    "unitNo": 3,
    "name": "Unit 3",
    "standards": [
      "RF.3.4a",
      "RF.3.4b",
      "RF.3.4c",
      "RL.3.7",
      "RL.3.9",
      "RL.3.10",
      "RI.3.7",
      "RI.3.8",
      "RI.3.9",
      "L.3.5c",
      "L.3.6",
      "L.3.1",
      "L.3.2"
    ],
    "examId": "g3-unit-3-exam"
  },
  {
    "id": "g3-u4",
    "grade": "3rd Grade",
    "band": 3,
    "unitNo": 4,
    "name": "Unit 4",
    "standards": [
      "RI.3.10",
      "L.3.3"
    ],
    "examId": "g3-unit-4-exam"
  },
  {
    "id": "g4-u1",
    "grade": "4th Grade",
    "band": 4,
    "unitNo": 1,
    "name": "Unit 1",
    "standards": [
      "RF.4.3",
      "RL.4.1",
      "RL.4.2",
      "RL.4.3",
      "RI.4.1",
      "RI.4.2",
      "RI.4.3",
      "L.4.4",
      "L.4.4a",
      "L.4.4b"
    ],
    "examId": "g4-unit-1-exam"
  },
  {
    "id": "g4-u2",
    "grade": "4th Grade",
    "band": 4,
    "unitNo": 2,
    "name": "Unit 2",
    "standards": [
      "RF.4.3a",
      "RL.4.4",
      "RL.4.5",
      "RL.4.6",
      "RI.4.4",
      "RI.4.5",
      "RI.4.6",
      "L.4.4c",
      "L.4.5",
      "L.4.5a"
    ],
    "examId": "g4-unit-2-exam"
  },
  {
    "id": "g4-u3",
    "grade": "4th Grade",
    "band": 4,
    "unitNo": 3,
    "name": "Unit 3",
    "standards": [
      "RF.4.4",
      "RL.4.7",
      "RL.4.9",
      "RL.4.10",
      "RI.4.7",
      "RI.4.8",
      "RI.4.9",
      "L.4.5b",
      "L.4.5c",
      "L.4.6"
    ],
    "examId": "g4-unit-3-exam"
  },
  {
    "id": "g4-u4",
    "grade": "4th Grade",
    "band": 4,
    "unitNo": 4,
    "name": "Unit 4",
    "standards": [
      "RI.4.10",
      "L.4.1",
      "L.4.2",
      "L.4.3"
    ],
    "examId": "g4-unit-4-exam"
  }
];

/** Graduation exam QuizDef id per band (may not exist in the manifest yet). */
export const GRADE_FINAL_ID: Record<Band, string> = { 0: "k-final", 1: "g1-final", 2: "g2-final", 3: "g3-final", 4: "g4-final" };
