#!/bin/bash

# Supabase Setup Script for Readee App
# This script automates the setup of local Supabase

set -e  # Exit on error

echo "🚀 Readee App - Supabase Setup Script"
echo "======================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if Docker is running
echo "📦 Checking Docker..."
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}❌ Docker is not running${NC}"
    echo ""
    echo "Please start Docker Desktop and run this script again."
    echo "Download Docker: https://www.docker.com/products/docker-desktop"
    exit 1
fi
echo -e "${GREEN}✅ Docker is running${NC}"
echo ""

# Check if .env.local exists and has placeholders
if [ -f .env.local ]; then
    if grep -q "your-project-url-here" .env.local 2>/dev/null || grep -q "http://127.0.0.1:54321" .env.local 2>/dev/null; then
        echo "📝 Found .env.local with placeholder values"
    else
        echo -e "${YELLOW}⚠️  .env.local exists and may have custom values${NC}"
        read -p "Do you want to overwrite it with local Supabase credentials? (y/N) " -n 1 -r
        echo ""
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Keeping existing .env.local"
            echo "You can manually update it using the guide in SUPABASE_CONNECTION_GUIDE.md"
            exit 0
        fi
    fi
fi

# Install Supabase CLI if not already installed
if ! npm list supabase > /dev/null 2>&1; then
    echo "📥 Installing Supabase CLI..."
    npm install supabase --save-dev
    echo -e "${GREEN}✅ Supabase CLI installed${NC}"
    echo ""
else
    echo -e "${GREEN}✅ Supabase CLI already installed${NC}"
    echo ""
fi

# Check if Supabase is already running
if npx supabase status > /dev/null 2>&1; then
    echo -e "${YELLOW}⚠️  Supabase is already running${NC}"
    read -p "Do you want to restart it? (y/N) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "🔄 Stopping Supabase..."
        npx supabase stop
        echo "🚀 Starting Supabase..."
        npx supabase start
    fi
else
    echo "🚀 Starting local Supabase..."
    echo "⏳ This may take 5-10 minutes the first time (downloading Docker images)..."
    echo ""
    npx supabase start
fi

echo ""
echo -e "${GREEN}✅ Supabase is running!${NC}"
echo ""

# Update .env.local with local credentials
echo "📝 Updating .env.local with local credentials..."

cat > .env.local << 'EOF'
# Supabase Configuration - Local Development
# Auto-generated by setup script

# Local Supabase (Development)
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU

# Note: These are the standard local development credentials
# For production, use remote Supabase credentials
# See SUPABASE_CONNECTION_GUIDE.md for details
EOF

echo -e "${GREEN}✅ .env.local updated${NC}"
echo ""

# Check if migrations ran successfully
echo "🔍 Verifying database setup..."
if npx supabase db reset --db-url "postgresql://postgres:postgres@127.0.0.1:54322/postgres" > /dev/null 2>&1; then
    echo -e "${GREEN}✅ Database migrations completed${NC}"
else
    echo -e "${YELLOW}⚠️  Could not verify migrations. They should have run automatically.${NC}"
fi
echo ""

echo "======================================"
echo -e "${GREEN}🎉 Setup Complete!${NC}"
echo "======================================"
echo ""
echo "📍 Next Steps:"
echo "   1. Start the dev server: npm run dev"
echo "   2. Visit: http://localhost:3000/test-connection"
echo "   3. All tests should pass ✅"
echo ""
echo "🎯 Useful URLs:"
echo "   - App: http://localhost:3000"
echo "   - Supabase Studio: http://127.0.0.1:54323"
echo "   - Test Connection: http://localhost:3000/test-connection"
echo ""
echo "📚 Documentation:"
echo "   - SUPABASE_CONNECTION_GUIDE.md - Full setup guide"
echo "   - ENV_SETUP.md - Environment setup details"
echo ""
echo "💡 Useful Commands:"
echo "   - npx supabase status  # Check Supabase status"
echo "   - npx supabase stop    # Stop Supabase"
echo "   - npx supabase start   # Start Supabase"
echo ""
echo "Happy coding! 🚀"
