@echo off
REM Supabase Setup Script for Readee App (Windows)
REM This script automates the setup of local Supabase

echo.
echo ==========================================
echo  Readee App - Supabase Setup Script
echo ==========================================
echo.

REM Check if Docker is running
echo Checking Docker...
docker info >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Docker is not running
    echo.
    echo Please start Docker Desktop and run this script again.
    echo Download Docker: https://www.docker.com/products/docker-desktop
    pause
    exit /b 1
)
echo [OK] Docker is running
echo.

REM Check if .env.local exists
if exist .env.local (
    findstr /C:"your-project-url-here" .env.local >nul 2>&1
    if %errorlevel% equ 0 (
        echo Found .env.local with placeholder values
    ) else (
        findstr /C:"http://127.0.0.1:54321" .env.local >nul 2>&1
        if %errorlevel% equ 0 (
            echo Found .env.local with local values
        ) else (
            echo [WARNING] .env.local exists and may have custom values
            set /p REPLY="Do you want to overwrite it with local Supabase credentials? (y/N) "
            if /i not "%REPLY%"=="y" (
                echo Keeping existing .env.local
                echo You can manually update it using the guide in SUPABASE_CONNECTION_GUIDE.md
                pause
                exit /b 0
            )
        )
    )
)

REM Check if Supabase CLI is installed
echo Checking Supabase CLI...
call npm list supabase >nul 2>&1
if %errorlevel% neq 0 (
    echo Installing Supabase CLI...
    call npm install supabase --save-dev
    echo [OK] Supabase CLI installed
    echo.
) else (
    echo [OK] Supabase CLI already installed
    echo.
)

REM Check if Supabase is already running
echo Checking Supabase status...
call npx supabase status >nul 2>&1
if %errorlevel% equ 0 (
    echo [WARNING] Supabase is already running
    set /p REPLY="Do you want to restart it? (y/N) "
    if /i "%REPLY%"=="y" (
        echo Stopping Supabase...
        call npx supabase stop
        echo Starting Supabase...
        call npx supabase start
    )
) else (
    echo Starting local Supabase...
    echo This may take 5-10 minutes the first time (downloading Docker images)...
    echo.
    call npx supabase start
)

echo.
echo [OK] Supabase is running!
echo.

REM Update .env.local with local credentials
echo Updating .env.local with local credentials...

(
echo # Supabase Configuration - Local Development
echo # Auto-generated by setup script
echo.
echo # Local Supabase ^(Development^)
echo NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
echo NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
echo SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
echo.
echo # Note: These are the standard local development credentials
echo # For production, use remote Supabase credentials
echo # See SUPABASE_CONNECTION_GUIDE.md for details
) > .env.local

echo [OK] .env.local updated
echo.

echo ==========================================
echo  Setup Complete!
echo ==========================================
echo.
echo Next Steps:
echo    1. Start the dev server: npm run dev
echo    2. Visit: http://localhost:3000/test-connection
echo    3. All tests should pass
echo.
echo Useful URLs:
echo    - App: http://localhost:3000
echo    - Supabase Studio: http://127.0.0.1:54323
echo    - Test Connection: http://localhost:3000/test-connection
echo.
echo Documentation:
echo    - SUPABASE_CONNECTION_GUIDE.md - Full setup guide
echo    - ENV_SETUP.md - Environment setup details
echo.
echo Useful Commands:
echo    - npx supabase status  # Check Supabase status
echo    - npx supabase stop    # Stop Supabase
echo    - npx supabase start   # Start Supabase
echo.
echo Happy coding!
echo.
pause
