/**
 * Curriculum NAVIGATION data: which lessons exist, in what order, under which
 * standard. Roughly 56 KB, generated by scripts/build-curriculum-manifest.ts.
 *
 * Use this anywhere a client surface needs to know the SHAPE of the curriculum -
 * the dashboard's next-lesson card, the journey map, progress counting. Use the
 * real files (`app/data/sample-lessons.json`, `lib/data/all-standards`) only
 * where lesson bodies or question banks are actually taught: /learn, /practice.
 *
 * Why the split: the dashboard is a client component and the first screen after
 * login. Importing the catalogue and all five question banks there put ~4 MB of
 * curriculum JSON into the browser bundle before a child chose anything. The
 * navigation surfaces read four fields per lesson and one standard's title.
 *
 * ‼️ Regenerate after editing the catalogue:
 *     npx tsx scripts/build-curriculum-manifest.ts
 */
import manifest from "@/app/data/curriculum-manifest.json";
import type { GradeKey } from "@/lib/assessment/questions";

/** Exactly the fields navigation reads. Matches CatalogLesson in lib/journey/next-lesson.ts. */
export type LessonMeta = {
  id: string;
  standardId: string;
  grade: string;
  domain: string;
  title: string;
};

/** A standard without its ten questions. */
export type StandardMeta = {
  standard_id: string;
  standard_description: string;
  domain: string;
};

const data = manifest as { lessons: LessonMeta[]; standards: Record<string, StandardMeta[]> };

/** Real grades only, so a lookup never scans the pre-k alias twice. */
const GRADE_ORDER = ["kindergarten", "1st", "2nd", "3rd", "4th"];

/** Every lesson in catalogue order, metadata only. */
export const LESSON_META: LessonMeta[] = data.lessons;

/**
 * Standards for a grade, titles only. Mirrors getStandardsForGrade's fallback:
 * pre-k reads kindergarten, and so does an unknown key.
 */
export function getStandardMetaForGrade(gradeKey: GradeKey | string): StandardMeta[] {
  if (gradeKey === "pre-k") return data.standards.kindergarten;
  return data.standards[gradeKey] ?? data.standards.kindergarten;
}

/**
 * A single standard's title by ID, searched across every grade.
 *
 * Metadata twin of findStandardById in lib/data/all-standards. Reach for the
 * full version only when the standard's QUESTIONS are needed; surfaces that
 * just want to print "what skill is this?" want this one.
 */
export function findStandardMetaById(standardId: string): StandardMeta | undefined {
  for (const grade of GRADE_ORDER) {
    const found = data.standards[grade]?.find((s) => s.standard_id === standardId);
    if (found) return found;
  }
  return undefined;
}

/** Every standard's title across all five grades, in grade order. */
export function getAllStandardMeta(): StandardMeta[] {
  return GRADE_ORDER.flatMap((g) => data.standards[g] ?? []);
}
