/**
 * Loader for Readee's standards-aligned question bank. Powers the
 * public SEO pages at /standards/[slug] — each Common Core ELA
 * standard becomes a landing page with the 3 free sample questions
 * and an upgrade CTA.
 *
 * Slugs are URL-safe lowercase (RL.K.1 → rl-k-1, RF.1.3a → rf-1-3a)
 * so search engines index them cleanly.
 */

import kJson from "@/app/data/kindergarten-standards-questions.json";
import g1Json from "@/app/data/1st-grade-standards-questions.json";
import g2Json from "@/app/data/2nd-grade-standards-questions.json";
import g3Json from "@/app/data/3rd-grade-standards-questions.json";
import g4Json from "@/app/data/4th-grade-standards-questions.json";
import type { Locale } from "@/lib/i18n/strings";

export type StandardQuestion = {
  id: string;
  type: string;
  prompt: string;
  choices?: string[];
  correct: string | string[];
  hint: string;
  difficulty: number;
  audio_url?: string;
  hint_audio_url?: string;
  image_url?: string;
};

export type Standard = {
  standard_id: string;
  standard_description: string;
  domain: string;
  parent_tip?: string;
  grade: "kindergarten" | "1st-grade" | "2nd-grade" | "3rd-grade" | "4th-grade";
  gradeLabel: string;
  questions: StandardQuestion[];
};

const GRADE_BANKS = [
  { grade: "kindergarten" as const, label: "Kindergarten", json: kJson },
  { grade: "1st-grade" as const, label: "1st Grade", json: g1Json },
  { grade: "2nd-grade" as const, label: "2nd Grade", json: g2Json },
  { grade: "3rd-grade" as const, label: "3rd Grade", json: g3Json },
  { grade: "4th-grade" as const, label: "4th Grade", json: g4Json },
];

export function slugifyStandard(id: string): string {
  return id.toLowerCase().replace(/\./g, "-");
}

export function unslugifyToIdCandidate(slug: string): string {
  // rl-k-1 → RL.K.1    ;   rf-1-3a → RF.1.3a
  // Uppercase the leading domain code (RL/RI/RF/SL/L/W), join on dots.
  const parts = slug.split("-");
  if (parts.length < 3) return slug.toUpperCase();
  const head = parts[0].toUpperCase();
  const grade = parts[1].toUpperCase(); // K, 1, 2, 3, 4
  const rest = parts.slice(2).join("");
  return `${head}.${grade}.${rest}`;
}

export function getAllStandards(): Standard[] {
  const out: Standard[] = [];
  for (const { grade, label, json } of GRADE_BANKS) {
    const bank = json as any;
    for (const s of bank.standards ?? []) {
      out.push({
        standard_id: s.standard_id,
        standard_description: s.standard_description,
        domain: s.domain,
        parent_tip: s.parent_tip,
        grade,
        gradeLabel: label,
        questions: s.questions ?? [],
      });
    }
  }
  return out;
}

/**
 * Async loader that serves the requested locale when translated JSON
 * is available on disk, else falls back to English. Used at runtime
 * by the practice page when the child's profile.language is 'es'.
 *
 * Translated files live alongside the English banks with a `-es`
 * suffix, e.g. `kindergarten-standards-questions-es.json`. They're
 * produced by `scripts/translate-bank-to-spanish.js`.
 */
export async function getStandardBySlugLocalized(
  slug: string,
  locale: Locale,
): Promise<Standard | null> {
  const target = unslugifyToIdCandidate(slug);
  if (locale === "en") {
    return getStandardBySlug(slug);
  }
  // Try ES banks — lazy-load to avoid bundling Spanish JSON when not
  // translated yet. Falls through to English on any import failure.
  // ts-ignore on imports because the ES files may not exist yet (they
  // get generated by scripts/translate-bank-to-spanish.js).
  try {
    const [ek, e1, e2, e3, e4] = await Promise.all([
      // @ts-ignore — optional translated bank
      import("@/app/data/kindergarten-standards-questions-es.json").catch(() => null),
      // @ts-ignore
      import("@/app/data/1st-grade-standards-questions-es.json").catch(() => null),
      // @ts-ignore
      import("@/app/data/2nd-grade-standards-questions-es.json").catch(() => null),
      // @ts-ignore
      import("@/app/data/3rd-grade-standards-questions-es.json").catch(() => null),
      // @ts-ignore
      import("@/app/data/4th-grade-standards-questions-es.json").catch(() => null),
    ]);
    const pairs = [
      { grade: "kindergarten", label: "Kindergarten", mod: ek },
      { grade: "1st-grade", label: "1st Grade", mod: e1 },
      { grade: "2nd-grade", label: "2nd Grade", mod: e2 },
      { grade: "3rd-grade", label: "3rd Grade", mod: e3 },
      { grade: "4th-grade", label: "4th Grade", mod: e4 },
    ];
    for (const p of pairs) {
      const bank = (p.mod as any)?.default ?? p.mod;
      if (!bank) continue;
      for (const s of bank.standards ?? []) {
        if (s.standard_id === target) {
          return {
            standard_id: s.standard_id,
            standard_description: s.standard_description,
            domain: s.domain,
            parent_tip: s.parent_tip,
            grade: p.grade as Standard["grade"],
            gradeLabel: p.label,
            questions: s.questions ?? [],
          };
        }
      }
    }
  } catch {
    /* fall back to English */
  }
  return getStandardBySlug(slug);
}

export function getStandardBySlug(slug: string): Standard | null {
  const targetId = unslugifyToIdCandidate(slug);
  const all = getAllStandards();
  const hit = all.find((s) => s.standard_id === targetId);
  return hit ?? null;
}

/** Friendly short name for a Common Core code → used in meta titles. */
export function domainFriendlyName(domain: string): string {
  if (/literature/i.test(domain)) return "Reading: Literature";
  if (/informational/i.test(domain)) return "Reading: Informational Text";
  if (/foundational/i.test(domain)) return "Reading: Foundational Skills";
  if (/language/i.test(domain)) return "Language";
  if (/speaking/i.test(domain)) return "Speaking & Listening";
  if (/writing/i.test(domain)) return "Writing";
  return domain;
}
