import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Copyright + DMCA",
  description:
    "How to report copyright concerns about content on Readee, and our designated DMCA agent.",
};

export default function CopyrightPage() {
  return (
    <div className="mx-auto max-w-3xl py-8 px-4">
      <h1 className="text-3xl font-bold text-zinc-900 tracking-tight mb-2">
        Copyright + DMCA Notice
      </h1>
      <p className="text-sm text-zinc-400 mb-8">
        Last updated: April 2026
      </p>

      <div className="prose prose-zinc max-w-none space-y-8">
        <section>
          <h2 className="text-xl font-bold text-zinc-900 mb-3">Overview</h2>
          <p>
            Readee respects intellectual property rights. Some content on
            Readee is generated by AI in response to prompts from teachers,
            parents, or our own daily-content systems. AI-generated text and
            images can occasionally resemble copyrighted material. If you
            believe content on Readee infringes a copyright you own or
            represent, we want to know — and we&apos;ll act quickly.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-zinc-900 mb-3">
            Designated DMCA Agent
          </h2>
          <p>
            Readee is registered with the U.S. Copyright Office under the
            Digital Millennium Copyright Act. Send formal takedown notices
            to our designated agent:
          </p>
          <div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4 not-prose font-mono text-sm">
            <div>Readee Learning LLC</div>
            <div>Attn: DMCA Agent</div>
            <div>81 Culver Street</div>
            <div>Somerset, NJ 08873</div>
            <div className="mt-2">
              Email:{" "}
              <a
                href="mailto:hello@readee.app"
                className="text-indigo-600 hover:underline"
              >
                hello@readee.app
              </a>{" "}
              (subject line: &quot;DMCA Notice&quot;)
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-bold text-zinc-900 mb-3">
            What to include in a takedown notice
          </h2>
          <p>
            Per 17 U.S.C. § 512(c)(3), a valid notice must include:
          </p>
          <ol className="list-decimal pl-6 space-y-1">
            <li>Your physical or electronic signature.</li>
            <li>
              A description of the copyrighted work you claim has been
              infringed.
            </li>
            <li>
              The specific URL on Readee where the allegedly infringing
              material appears.
            </li>
            <li>
              Your name, address, phone number, and email so we can contact
              you.
            </li>
            <li>
              A statement that you have a good-faith belief the use is not
              authorized by the copyright owner, its agent, or the law.
            </li>
            <li>
              A statement, made under penalty of perjury, that the
              information in your notice is accurate and that you are the
              copyright owner or authorized to act on the owner&apos;s
              behalf.
            </li>
          </ol>
        </section>

        <section>
          <h2 className="text-xl font-bold text-zinc-900 mb-3">
            What happens after you send a notice
          </h2>
          <p>
            We aim to remove or disable access to the reported content
            within 24 hours of receiving a valid notice. We&apos;ll notify
            the user who created or prompted the content and pass along
            your notice. If they file a counter-notice, we&apos;ll forward
            it to you and follow the DMCA counter-notice procedure.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-zinc-900 mb-3">
            Repeat-infringer policy
          </h2>
          <p>
            Users whose content generates two valid takedown notices will
            receive a written warning and lose access to AI generation
            features. A third valid notice results in account termination.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-zinc-900 mb-3">
            User-generated and AI-generated content
          </h2>
          <p>
            When a teacher, parent, or student prompts Readee&apos;s AI to
            generate content, that user is responsible for the topics they
            submit and the resulting output. Readee provides AI tools as a
            platform but does not pre-approve every prompt. By using
            Readee&apos;s AI features, users warrant that their prompts and
            the resulting content do not knowingly infringe third-party
            rights. See our{" "}
            <Link
              href="/terms-of-service"
              className="text-indigo-600 hover:underline"
            >
              Terms of Service
            </Link>{" "}
            for the full allocation of responsibilities.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-bold text-zinc-900 mb-3">
            False claims
          </h2>
          <p>
            Sending a knowingly false takedown notice is illegal under 17
            U.S.C. § 512(f) and you may be liable for damages and
            attorneys&apos; fees. Please be certain before you file.
          </p>
        </section>
      </div>
    </div>
  );
}
