/**
 * docs/UNIT_ROADMAP.md → lib/journey-v2/roadmap.gen.ts
 *
 * The roadmap is the V2 spine: one unit = one block of standards in factory
 * order. This turns the checkable markdown into data the journey can import,
 * so a unit appears on a child's map the moment its lessons land in the
 * manifest, and never before. Re-run after editing the roadmap:
 *
 *   npx tsx scripts/roadmap-to-ts.ts
 */
import { promises as fs } from "node:fs";

const SRC = "docs/UNIT_ROADMAP.md";
const OUT = "lib/journey-v2/roadmap.gen.ts";

type Band = 0 | 1 | 2 | 3 | 4;
type Unit = { id: string; grade: string; band: Band; unitNo: number; name: string; standards: string[]; examId: string };

const GRADE_BY_HEADER: Record<string, { grade: string; band: Band; key: string }> = {
  Kindergarten: { grade: "Kindergarten", band: 0, key: "k" },
  "Grade 1": { grade: "1st Grade", band: 1, key: "g1" },
  "Grade 2": { grade: "2nd Grade", band: 2, key: "g2" },
  "Grade 3": { grade: "3rd Grade", band: 3, key: "g3" },
  "Grade 4": { grade: "4th Grade", band: 4, key: "g4" },
};

function examIdFor(band: Band, unitNo: number): string {
  // K exams shipped before the grade prefix convention existed.
  return band === 0 ? `unit-${unitNo}-exam` : `${GRADE_BY_HEADER[band === 1 ? "Grade 1" : band === 2 ? "Grade 2" : band === 3 ? "Grade 3" : "Grade 4"].key}-unit-${unitNo}-exam`;
}

async function main() {
  const md = await fs.readFile(SRC, "utf-8");
  const units: Unit[] = [];
  let cur: { grade: string; band: Band; key: string } | null = null;
  let unit: Unit | null = null;
  for (const raw of md.split("\n")) {
    const line = raw.trim();
    const g = line.match(/^## (Kindergarten|Grade [1-4])\b/);
    if (g) { cur = GRADE_BY_HEADER[g[1]]; unit = null; continue; }
    if (/^## /.test(line)) { cur = null; unit = null; continue; } // finals / rules
    const u = line.match(/^### (?:K|G[1-4])·U(\d+)(?:\s+[—-]\s+([^✅]+?))?\s*(?:✅.*)?$/);
    if (u && cur) {
      const unitNo = Number(u[1]);
      const name = (u[2] ?? "").trim() || `Unit ${unitNo}`;
      unit = { id: `${cur.key}-u${unitNo}`, grade: cur.grade, band: cur.band, unitNo, name, standards: [], examId: examIdFor(cur.band, unitNo) };
      units.push(unit);
      continue;
    }
    // "RF.K.1a", "L.2.4b", and the K language rows written as "K.L.6"
    const row = line.match(/^\|\s*[☐☑]\s*\|\s*([A-Z]+\.[A-Z0-9]+\.[0-9]+[a-z]?)\s*\|/);
    if (row && unit && !unit.standards.includes(row[1])) unit.standards.push(row[1]);
  }
  const body = `// AUTO-GENERATED by scripts/roadmap-to-ts.ts from docs/UNIT_ROADMAP.md. Do not edit by hand.
// The V2 spine: every unit in factory order with the standards it teaches.
// A unit's lessons are resolved from the lesson manifest at runtime
// (lib/journey-v2/catalog.ts), so this file never claims a lesson exists.

export type Band = 0 | 1 | 2 | 3 | 4;

export interface RoadmapUnit {
  /** "k-u1", "g2-u3" */
  id: string;
  /** Catalog grade string, matches LessonDef.grade: "Kindergarten", "2nd Grade" */
  grade: string;
  band: Band;
  unitNo: number;
  /** Roadmap name when the roadmap has one, else "Unit N" */
  name: string;
  /** CCSS ids in roadmap order */
  standards: string[];
  /** QuizDef id of the unit exam (may not exist in the manifest yet) */
  examId: string;
}

export const ROADMAP_UNITS: RoadmapUnit[] = ${JSON.stringify(units, null, 2)};

/** Graduation exam QuizDef id per band (may not exist in the manifest yet). */
export const GRADE_FINAL_ID: Record<Band, string> = { 0: "k-final", 1: "g1-final", 2: "g2-final", 3: "g3-final", 4: "g4-final" };
`;
  await fs.writeFile(OUT, body);
  const total = units.reduce((n, u) => n + u.standards.length, 0);
  console.log(`${units.length} units, ${total} standards → ${OUT}`);
  for (const u of units) console.log(`  ${u.id.padEnd(6)} ${u.name.padEnd(22)} ${u.standards.length} std  exam ${u.examId}`);
}
main().catch((e) => { console.error(e); process.exit(1); });
