-- Daily question of the day. Generated by a Vercel cron at 5am ET,
-- one row per calendar date. Theme is picked from a date-aware theme
-- bank (holidays, seasons, fun-fact days, monthly observances).
--
-- Surfaces on parent dashboard, teacher classroom, and a public
-- /today SEO page. The QC engine runs after generation; rows where
-- qc_overall = 'fail' get auto-regenerated once before falling back
-- to yesterday's question.

create table public.daily_questions (
  date date primary key,
  theme text not null,
  slug text not null unique,
  passage_title text not null,
  passage_body text not null,
  image_url text,
  audio_url text,
  question_prompt text not null,
  choices jsonb not null,
  correct text not null,
  hint text,
  extra_questions jsonb,
  qc_overall text not null default 'pass'
    check (qc_overall in ('pass','warn','fail')),
  qc_report jsonb,
  views integer not null default 0,
  thumbs_up integer not null default 0,
  thumbs_down integer not null default 0,
  created_at timestamptz not null default now()
);

create index daily_questions_date_idx on public.daily_questions (date desc);

alter table public.daily_questions enable row level security;

create policy "Anyone can read daily questions"
  on public.daily_questions for select
  using (true);

create or replace function public.bump_daily_question_engagement(
  p_date date,
  p_field text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_field = 'view' then
    update public.daily_questions set views = views + 1 where date = p_date;
  elsif p_field = 'up' then
    update public.daily_questions set thumbs_up = thumbs_up + 1 where date = p_date;
  elsif p_field = 'down' then
    update public.daily_questions set thumbs_down = thumbs_down + 1 where date = p_date;
  end if;
end;
$$;

grant execute on function public.bump_daily_question_engagement(date, text) to anon, authenticated;
