-- Parent-facing AI "flash snapshot" cache.
-- Generated by Gemini Flash from deterministic facts (see lib/ai/build-parent-snapshot.ts),
-- cached per child and refreshed at most once per calendar day so the analytics page
-- never re-bills a model call on every visit. Also becomes the weekly-email body later.
alter table public.children
  add column if not exists ai_snapshot     jsonb,
  add column if not exists ai_snapshot_at  timestamptz;
