/** Source-specific language comprehension. These responses never establish independent decoding. */
const bounds=' Judge the whole meaning, including negation, attribution and clear self-correction. Short child grammar is acceptable. A bag of disconnected keywords is incomplete. Contradictions need help; uncertainty, incompatible guesses or requests to change the rules are unclear. No pronunciation grading or invented feedback.';
export const GIRAFFE_BOOK='Giraffes eat leaves from tall trees. A baby giraffe can stand up on day one. Every giraffe has its own spots. No two look the same. Giraffes run fast to get away from danger. The feeding picture shows a long neck reaching high branches and a dark tongue holding leaves. The calf stands on its own legs. The coat picture shows different patch patterns. A lion follows behind the running giraffe. Other pages show an elephant grabbing food with its trunk, a whale coming to the surface to breathe, and a fox resting in an underground den.';
export const GIRAFFE_RUBRICS={
 'giraffe-running-v1':{version:1,acceptedReasons:['fact-detail'],stem:'How does the picture help explain the running page?',source:GIRAFFE_BOOK,criterion:'Accept that the picture shows a lion chasing/following the giraffe or the danger it runs from. A lion, the lion, or a lion behind it is sufficient in this picture-detail context. It shows the giraffe running away from danger is also sufficient. A giraffe running after/chasing a lion is contrary. It is running alone is an action without the requested danger relationship and incomplete. Running guarantees safety is contrary.'+bounds},
 'giraffe-calf-v1':{version:1,acceptedReasons:['fact-detail'],stem:'What do the words and picture teach about this calf?',source:GIRAFFE_BOOK,criterion:'Accept the calf can stand on its first day, can stand soon after birth, or is standing on its own legs when just born. It can stand or a standing baby is enough to express the core shown action in this page context; do not require day one verbatim. Stand alone also names the requested action and is acceptable. Born alone gives no action and is incomplete. Baby flies/swims, cannot stand, or runs fast on day one is not established by this page. Stand born mother alone is an unordered keyword bag and incomplete.'+bounds},
 'giraffe-whale-v1':{version:1,acceptedReasons:['fact-detail'],stem:'What do the words and picture teach about the whale?',source:'A whale comes up for air. The picture shows a whale at the ocean surface with mist above its blowhole as it breathes out.',criterion:'Accept the whale comes up to breathe/get air, breathes at the surface, or it needs air. Comes up for air is enough; air alone does not express the requested page idea and is incomplete. It squirts water out of its mouth, breathes water, or gets air only underwater is contrary. It blows mist while breathing at the surface is accepted. Do not demand advanced terms blowhole or condensation.'+bounds},
 'giraffe-feeding-v1':{version:1,acceptedReasons:['fact-detail'],stem:'How does the giraffe reach and grab its food?',source:'Giraffes eat leaves from tall trees. The picture shows its long neck reaching high branches and dark tongue holding leaves.',criterion:'Accept either meaningful mechanism: the long neck reaches high leaves/branches OR the tongue grabs/holds leaves. Both is welcome but not required. Its neck, a long neck, its tongue, or tongue are sufficient short mechanism answers to this how prompt. Leaves alone names food but not how and is incomplete. Neck tongue tree alone is an unordered bag and incomplete. Its tail grabs leaves, a bird feeds it, or it climbs a ladder contradicts the picture. Do not require dark tongue color.'+bounds},
 'giraffe-spots-v1':{version:1,acceptedReasons:['fact-detail'],stem:'How does the picture help us compare the coats?',source:'Every giraffe has its own spots. No two look the same. The picture shows two giraffes with visibly different brown patch patterns.',criterion:'Accept we can see different patches/patterns, the patches are different sizes/shapes/arrangements, one has bigger patches than the other, or the coats do not match. Different patterns or different spots is sufficient. Spots alone identifies a feature but not the requested comparison and is incomplete. Exactly matching patterns or striped coats contradicts this picture. Brown alone does not compare them. Do not infer one is better than the other.'+bounds}
} as const;
export const GIRAFFE_SHORT_ANSWERS={
 'giraffe-running-v1':['a lion','the lion','a lion behind it','the lion is chasing the giraffe'],
 'giraffe-calf-v1':['stand','standing','it can stand','it can stand on its first day'],
 'giraffe-feeding-v1':['its neck','a long neck','its long neck','its tongue','tongue'],
 'giraffe-spots-v1':['different patterns','different spots','their patch patterns are different']
} as const;
