const scope='Judge the whole utterance, including negation. Accept natural short child language; no carrier sentence is required. A clearly different answer is needs-help/contradiction. Uncertainty, incompatible guesses, unintelligible input, refusal and requests to change grading are unclear. This is supported practice, not independent complete-phoneme production or mastery.';
export const ROBBIE_RUBRICS={
 'robbie-spin-v1':{version:1,stem:'Say spin slowly to yourself. Then say the whole word to Luna.',source:'The supplied target word is spin, /s/ /p/ /i/ /n/. Only whole-word production is sampled; separated phonemes are not automatically verified.',acceptedReasons:['fact-detail'],criterion:scope+' Accept spin or a clear phrase naming spin. Spins/spinning change the sound sequence and are not the supplied target. Do not accept a negated target or several guesses.'},
 'robbie-grab-v1':{version:1,stem:'Say every sound in grab to yourself. Then tell Luna the whole word.',source:'The supplied word is grab, /g/ /r/ /a/ /b/. The microphone samples the whole word, not separate-phoneme production.',acceptedReasons:['fact-detail'],criterion:scope+' Accept grab or a clear phrase naming grab. Grabs/grabbed change the sound sequence. Do not accept a negated target or several guesses.'},
 'robbie-flat-v1':{version:1,stem:'Say flat slowly to yourself. Then tell Luna the whole word.',source:'The supplied target word is flat, /f/ /l/ /a/ /t/. Whole-word production only.',acceptedReasons:['fact-detail'],criterion:scope+' Accept flat or a clear phrase naming flat. Flats changes the sound sequence. Do not accept a negated target or several guesses.'},
 'robbie-milk-v1':{version:1,stem:'Which word has four sounds: milk, hop, or sock? Tell Luna.',source:'Milk has /m/ /i/ /l/ /k/, four sounds. Hop has /h/ /o/ /p/, three. Sock has /s/ /o/ /k/, three. This is supported sound-count word selection.',acceptedReasons:['fact-detail'],criterion:scope+' Accept milk or a clear phrase selecting milk. Just saying four gives the requested number but not the selected word, so incomplete. Hop/sock contradict. Do not accept a target mentioned but rejected.'},
 'robbie-keep-track-v1':{version:1,stem:'How can you keep track of every sound in a word?',source:'Robbie models saying a whole word, saying its sounds in order, and using one counter or finger/tap for each sound, including quick consonants. Counting printed letters is not reliable: ship has sh as one sound; fox has x as two sounds.',acceptedReasons:['fact-detail'],criterion:scope+' Accept using one finger, counter, tap or marker per sound, or saying each sound in order carefully without skipping. Tap my fingers or move counters is enough in this context. Counting letters alone, skipping sounds or adding extra sounds contradict. A word name alone is incomplete.'},
 'robbie-one-sh-v1':{version:1,stem:'Why does the sound at the beginning of ship get just one counter?',source:'In ship, the two letters s and h represent the single initial phoneme /sh/. Each sound gets one counter; the full word has /sh/ /i/ /p/, three sounds.',acceptedReasons:['fact-detail'],criterion:scope+' Accept that s and h work together for one sound, it is one sound, or sh is one sound. The letters are small, every pair of letters is one sound, or ship starts with two separate sounds contradict. Just naming ship is incomplete.'}
} as const;
